#!/usr/bin/env node
// build-browser.mjs — the ONE browser build of @xmbl/lng, generated from the SAME src/*.js the node runs.
//
// XMBL is modular: a consumer IMPORTS a module, it never copies one. This turns the package's ESM sources
// into a single-file ES module (dist/lng.browser.js) that a <script type="module">, an import map, or any
// bundler loads as-is — no Node built-ins, no dependencies, no build tool. The output is a pure function of
// src/*.js + package.json (no timestamps, no toolchain), so it is byte-reproducible, and the committed
// artifact is gate-checked against a fresh build (src/browser-bundle.test.mjs): the browser bytes cannot
// drift from the language the node runs, and nobody has a reason to hand-port it again.
//
//   node build-browser.mjs            # (re)writes dist/lng.browser.js
//   node build-browser.mjs --check    # exit 1 if the committed artifact differs from a fresh build
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
export const BROWSER_BUNDLE = join(HERE, 'dist', 'lng.browser.js');

// The package's modules in dependency order: lng.js imports nothing; every later file imports only from
// earlier ones (enforced below — a cycle or a forward import is a build error, not a silent TDZ crash).
const MODULES = ['lng', 'typecheck', 'transpile-evm', 'compile-wasm', 'import-solidity'];
const ident = (file) => '__' + file.replace(/-/g, '_');

// Rewrite one ESM source file into a scoped script: `import {…} from './x.js'` becomes a destructure of the
// already-built module object, `export` declarations become plain declarations, and the file's export list
// becomes the scope's return value. Any import/export form this does not understand is a HARD error — the
// build must never emit something that merely looks like a bundle.
function scopeModule(file, src) {
  const exported = [];
  const lines = src.split('\n').map((line, i) => {
    const at = `src/${file}.js:${i + 1}`;
    let m;
    if ((m = line.match(/^import\s*\{([^}]*)\}\s*from\s*'\.\/([\w-]+)\.js';?\s*$/))) {
      const dep = m[2];
      if (!MODULES.includes(dep)) throw new Error(`${at}: import of a file outside the module list: ${dep}.js`);
      if (MODULES.indexOf(dep) >= MODULES.indexOf(file)) throw new Error(`${at}: ${dep}.js must be built before ${file}.js (dependency order)`);
      if (/\bas\b/.test(m[1])) throw new Error(`${at}: renamed import (as) is not supported by the bundler`);
      return `const {${m[1]}} = ${ident(dep)};`;
    }
    if ((m = line.match(/^export\s*\{([^}]*)\};?\s*$/))) {
      const names = m[1].split(',').map((s) => s.trim()).filter(Boolean);
      for (const n of names) if (!/^[\w$]+$/.test(n)) throw new Error(`${at}: unsupported export specifier '${n}'`);
      exported.push(...names);
      return '';
    }
    if ((m = line.match(/^export\s+(?:async\s+)?(?:function\*?|class|const|let|var)\s+([\w$]+)/))) {
      exported.push(m[1]);
      return line.replace(/^export\s+/, '');
    }
    if (/^(import|export)\b/.test(line)) throw new Error(`${at}: unsupported import/export form: ${line}`);
    return line;
  });
  if (exported.length === 0) throw new Error(`src/${file}.js exports nothing`);
  return { body: lines.join('\n'), exported };
}

/** The browser bundle's source text — a pure function of src/*.js and package.json. */
export function buildBrowserBundle() {
  const pkg = JSON.parse(readFileSync(join(HERE, 'package.json'), 'utf8'));
  const scopes = [];
  const surface = [];
  for (const file of MODULES) {
    const { body, exported } = scopeModule(file, readFileSync(join(HERE, 'src', `${file}.js`), 'utf8'));
    scopes.push(`// ── src/${file}.js ──\nconst ${ident(file)} = (() => {\n${body}\nreturn { ${exported.join(', ')} };\n})();\n`);
    surface.push(`export const { ${exported.join(', ')} } = ${ident(file)};`);
  }
  return [
    `// @xmbl/lng ${pkg.version} — browser build. GENERATED by build-browser.mjs from src/*.js; DO NOT EDIT.`,
    '// The same sources the node runs, as one dependency-free ES module: import it, never copy it.',
    '// The gate (src/browser-bundle.test.mjs) rebuilds this file and fails on any byte of drift.',
    "'use strict';",
    '',
    ...scopes,
    '// ── public surface (the same names index.js exports) ──',
    `export const VERSION = ${JSON.stringify(pkg.version)};`,
    ...surface,
    '',
  ].join('\n');
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const fresh = buildBrowserBundle();
  if (process.argv.includes('--check')) {
    let committed = null;
    try { committed = readFileSync(BROWSER_BUNDLE, 'utf8'); } catch { /* absent counts as drift */ }
    if (committed !== fresh) { console.error(`DRIFT: ${BROWSER_BUNDLE} differs from a fresh build (run: node build-browser.mjs)`); process.exit(1); }
    console.log(`ok: ${BROWSER_BUNDLE} matches a fresh build (${fresh.length} bytes)`);
  } else {
    mkdirSync(dirname(BROWSER_BUNDLE), { recursive: true });
    writeFileSync(BROWSER_BUNDLE, fresh);
    console.log(`wrote ${BROWSER_BUNDLE} (${fresh.length} bytes)`);
  }
}
