// air.js — GENERAL-PURPOSE zero-knowledge over the XMBL curve field.
//
// `xzk.js` proves ONE statement: that a committed curve passes through given points. Useful, but
// the statement is fixed. This proves ARBITRARY computation: a caller supplies an execution trace
// and the polynomial constraints that a correct execution must satisfy, and gets a proof that some
// trace satisfying them exists — without revealing it. Fibonacci, a hash chain, a state machine, a
// VM step function: anything expressible as "each row follows from the previous one" fits.
//
// It is the same machinery underneath — the BabyBear field, the quartic extension for challenges,
// Merkle commitments, FRI, grinding — applied to a general constraint system (an AIR) instead of
// one hardcoded curve statement.
//
// HOW IT WORKS
//   1. The trace is T rows by W columns. Interpolate each column over a size-T subgroup, so row r
//      is the column polynomial at g^r.
//   2. BLIND each column: col'(x) = col(x) + (x^T − 1)·r(x) with r random. Since x^T − 1 vanishes
//      on the whole trace domain, col' agrees with col on every row — the constraints are
//      untouched — while being random everywhere else. The blind's degree is set above the number
//      of openings, so the opened points never determine the polynomial.
//   3. Evaluate on a COSET of a larger domain (size N = K·blowup). A coset, so the evaluation
//      domain is disjoint from the trace domain and no denominator is ever zero.
//   4. Commit each column. Draw batching challenges from the ~124-bit extension field.
//   5. Build the COMPOSITION: Σ α_k·(transition_k / Z_T) + Σ β_j·(boundary_j / (x − g^row)), where
//      Z_T = (x^T − 1)/(x − g^(T−1)) vanishes on every row a transition must hold on. It is a
//      polynomial exactly when the constraints hold; otherwise the division leaves a high-degree
//      remainder that FRI rejects.
//   6. Prove the composition is low-degree with FRI, and open the trace at random points so the
//      verifier can recompute the composition there and compare.
//
// The verifier never sees the trace. It sees commitments, a low-degree proof, and a few openings of
// a blinded polynomial.

import { randomBytes } from 'node:crypto';
import {
  p, mod, add, sub, mul, inv, pw, polyEval, domainOfSize, merkle, merkleExt, mpath, mverify,
  mverifyExt, H, fsExt, fsIndex, friProve, friVerify, eAdd, eScale, eFrom, eEq, eStr,
  GRIND_BITS, EXT_BITS,
} from './fri.js';

const polyAdd = (a, b) => { const n = Math.max(a.length, b.length); return Array.from({ length: n }, (_, i) => add(a[i] || 0n, b[i] || 0n)); };
const polyMul = (a, b) => { const r = new Array(a.length + b.length - 1).fill(0n); for (let i = 0; i < a.length; i++) for (let j = 0; j < b.length; j++) r[i + j] = add(r[i + j], mul(a[i], b[j])); return r; };
const nextPow2 = (x) => { let k = 1; while (k < x) k <<= 1; return k; };

/**
 * Interpolate T values over the size-T subgroup generated by g, by inverse DFT. O(T^2), which is
 * what the small traces here want; an NTT would matter at a scale this does not reach.
 */
function interpOverSubgroup(values, g, T) {
  const gInv = inv(g), Tinv = inv(BigInt(T));
  const out = new Array(T).fill(0n);
  // c_k = (1/T) * sum_r values[r] * g^(-r k)
  for (let k = 0; k < T; k++) {
    let acc = 0n, w = 1n;               // w = g^(-r k) as r advances
    const step = pw(gInv, BigInt(k));
    for (let r = 0; r < T; r++) { acc = add(acc, mul(values[r], w)); w = mul(w, step); }
    out[k] = mul(acc, Tinv);
  }
  return out;
}

/**
 * Size the proof system for a given computation.
 * @param {object} o
 * @param {number} o.traceLen       rows (power of two)
 * @param {number} o.width          columns
 * @param {number} o.constraintDeg  highest total degree of any transition constraint in the columns
 * @param {number} [o.blowup=8]     N / K — lower rate, more soundness per query
 * @param {number} [o.nq=96]        FRI queries
 * @param {number} [o.nc=16]        trace openings
 */
export function setup(o) {
  const T = o.traceLen, W = o.width, D = o.constraintDeg;
  const blowup = o.blowup || 8, nq = o.nq || 96, nc = o.nc || 16;
  const grind = o.grindBits === undefined ? GRIND_BITS : o.grindBits;
  // The blind must out-degree everything the verifier gets to see: each opening reveals the column
  // at two points, so 2*nc values. Above that the opened points leave the polynomial undetermined.
  const blindDeg = o.blindDegree || (2 * nc + 8);
  const colDeg = 2 * T - 1 + blindDeg;            // deg(col + (x^T - 1)*r)
  const quotientDeg = D * colDeg - (T - 1);
  const K = nextPow2(Math.max(quotientDeg + 1, colDeg + 1));
  const N = K * blowup;
  // The field's 2-adicity is 27 (p - 1 = 2^27 * 15), so a domain above 2^27 has NO generator and
  // domainOfSize would silently return a bad one. The practical ceiling is lower than that.
  if (N > (1 << 22)) throw new Error(`air.setup: domain ${N} exceeds the practical ceiling (2^22); reduce the trace length or the constraint degree`);
  const g = pw(31n, (p - 1n) / BigInt(T));         // generator of the size-T trace subgroup
  const dom = domainOfSize(N);
  const SHIFT = 31n;                               // coset shift: 31 generates F_p*, so it is not
  if (pw(SHIFT, BigInt(N)) === 1n) throw new Error('air.setup: coset shift lies in the domain');
  const coset = dom.map((x) => mul(SHIFT, x));     //   in the size-N subgroup and the coset is disjoint
  if (N % T !== 0) throw new Error('air.setup: trace length must divide the domain');
  return { T, W, D, K, N, blowup, nq, nc, grind, blindDeg, g, dom, coset, shift: SHIFT, step: N / T, extBits: EXT_BITS };
}

/** Z_T(x) = (x^T − 1)/(x − g^(T−1)) — vanishes on every row a transition must hold on. */
const zTransition = (ctx, x) => mul(sub(pw(x, BigInt(ctx.T)), 1n), inv(sub(x, pw(ctx.g, BigInt(ctx.T - 1)))));

/**
 * Rebuild the Fiat-Shamir challenges. Prover and verifier run this, and it absorbs the WHOLE public
 * statement — every parameter and every boundary cell — not just the column roots.
 *
 * Roots alone would not be enough: two different statements that happen to share K and N would draw
 * the SAME batching challenges from the same commitments, and only the domain-size check in
 * friVerify would separate them. That is an accident of sizing, not a binding. With the parameters
 * and the boundary in the transcript, a proof is tied to the statement it was made for.
 */
function statementTag(ctx, nT, boundary) {
  return [ctx.T, ctx.W, ctx.D, ctx.K, ctx.N, ctx.blowup, ctx.nq, ctx.nc, ctx.grind, ctx.blindDeg, nT,
    boundary.map((b) => `${b.row}/${b.col}/${b.value.toString()}`).join(';')].join('|');
}
function challenges(roots, ctx, nT, boundary) {
  const t = H(statementTag(ctx, nT, boundary)) + ':' + roots.join(':');
  return {
    transcript: t,
    alphas: Array.from({ length: nT }, (_, k) => fsExt(t + ':alpha' + k)),
    betas: Array.from({ length: boundary.length }, (_, j) => fsExt(t + ':beta' + j)),
  };
}

/**
 * Prove that a trace satisfying the constraints exists.
 * @param {object} ctx from {@link setup}
 * @param {object} o
 * @param {bigint[][]} o.trace         T rows, each W field elements
 * @param {Function[]} o.transitions   (cur, nxt) => bigint, must be 0 on rows 0..T-2
 * @param {{row:number,col:number,value:bigint}[]} o.boundary  pinned cells (the public statement)
 */
export function prove(ctx, { trace, transitions, boundary }) {
  const { T, W, N, step, coset } = ctx;
  if (trace.length !== T) throw new Error(`prove: trace has ${trace.length} rows, expected ${T}`);
  // 1-2. interpolate each column and blind it with a multiple of (x^T - 1)
  const xT = new Array(T + 1).fill(0n); xT[T] = 1n; xT[0] = mod(-1n);
  const cols = [];
  for (let j = 0; j < W; j++) {
    const base = interpOverSubgroup(trace.map((r) => r[j]), ctx.g, T);
    const r = Array.from({ length: ctx.blindDeg + 1 }, () => mod(BigInt('0x' + randomBytes(32).toString('hex'))));
    cols.push(polyAdd(base, polyMul(xT, r)));
  }
  // 3. evaluate on the coset
  const evals = cols.map((c) => coset.map((x) => polyEval(c, x)));
  // 4. commit each column, then draw the batching challenges
  const coms = evals.map((e) => merkle(e));
  const roots = coms.map((c) => c.root);
  const { alphas, betas, transcript } = challenges(roots, ctx, transitions.length, boundary);
  // 5. compose
  const zInv = coset.map((x) => inv(zTransition(ctx, x)));
  const bInv = boundary.map((b) => coset.map((x) => inv(sub(x, pw(ctx.g, BigInt(b.row))))));
  const C = new Array(N);
  for (let i = 0; i < N; i++) {
    const ni = (i + step) % N;
    const cur = evals.map((e) => e[i]), nxt = evals.map((e) => e[ni]);
    let acc = eFrom(0n);
    for (let k = 0; k < transitions.length; k++) acc = eAdd(acc, eScale(alphas[k], mul(transitions[k](cur, nxt), zInv[i])));
    for (let j = 0; j < boundary.length; j++) acc = eAdd(acc, eScale(betas[j], mul(sub(cur[boundary[j].col], boundary[j].value), bInv[j][i])));
    C[i] = acc;
  }
  // 6. low-degree proof for the composition, plus trace openings
  const comC = merkleExt(C);
  const friC = friProve(C, coset, ctx.K, ctx.nq, ctx.grind, true);
  const idxs = Array.from({ length: ctx.nc }, (_, k) => fsIndex(comC.root + ':' + transcript + ':open' + k, N));
  const opens = idxs.map((i) => {
    const ni = (i + step) % N;
    return {
      i,
      cur: evals.map((e) => e[i]), nxt: evals.map((e) => e[ni]),
      pCur: coms.map((c) => mpath(c.tree, i)), pNxt: coms.map((c) => mpath(c.tree, ni)),
      Cv: C[i], pC: mpath(comC.tree, i),
    };
  });
  return { roots, rootC: comC.root, friC, opens };
}

/**
 * Verify. The verifier holds only the constraints, the boundary (the public statement) and the
 * proof — never the trace.
 */
export function verify(ctx, { proof, transitions, boundary }) {
  const { N, step, coset } = ctx;
  try {
    if (!Array.isArray(proof.roots) || proof.roots.length !== ctx.W) return false;
    if (proof.friC.roots[0] !== proof.rootC) return false;        // one codeword, not two
    if (!friVerify(proof.friC, coset, ctx.K, ctx.nq, ctx.grind, true)) return false;
    const { alphas, betas, transcript } = challenges(proof.roots, ctx, transitions.length, boundary);
    const idxs = Array.from({ length: ctx.nc }, (_, k) => fsIndex(proof.rootC + ':' + transcript + ':open' + k, N));
    if (proof.opens.length !== ctx.nc) return false;
    for (let k = 0; k < ctx.nc; k++) {
      const o = proof.opens[k], i = idxs[k], ni = (i + step) % N;
      if (o.i !== i) return false;
      for (let j = 0; j < ctx.W; j++) {
        if (!mverify(proof.roots[j], o.cur[j], i, o.pCur[j])) return false;
        if (!mverify(proof.roots[j], o.nxt[j], ni, o.pNxt[j])) return false;
      }
      if (!mverifyExt(proof.rootC, o.Cv, i, o.pC)) return false;
      const x = coset[i];
      const zInv = inv(zTransition(ctx, x));
      let acc = eFrom(0n);
      for (let t = 0; t < transitions.length; t++) acc = eAdd(acc, eScale(alphas[t], mul(transitions[t](o.cur, o.nxt), zInv)));
      for (let b = 0; b < boundary.length; b++) {
        acc = eAdd(acc, eScale(betas[b], mul(sub(o.cur[boundary[b].col], boundary[b].value), inv(sub(x, pw(ctx.g, BigInt(boundary[b].row)))))));
      }
      if (!eEq(acc, o.Cv)) return false;
    }
    return true;
  } catch { return false; }
}

// ── Named statements ─────────────────────────────────────────────────────────────────────────────
// A constraint system is JavaScript, so it cannot be chain-staged: staging one would be staging
// code to execute. A contract instead names a statement from THIS registry, and the only thing it
// supplies is the public value it claims. That keeps the verdict bound to bytes the contract chose
// while the constraints stay fixed, reviewable and identical on every node.

/** @type {Record<string, {params: object, transitions: Function[], boundary: (claimed: bigint) => object[], describe: string}>} */
export const STATEMENTS = {
  // "I ran the Fibonacci recurrence for 32 rows from (1,1) and got `claimed`."
  'fib-32': {
    params: { traceLen: 32, width: 2, constraintDeg: 1 },
    transitions: [(c, n) => sub(n[0], c[1]), (c, n) => sub(n[1], add(c[0], c[1]))],
    boundary: (claimed) => [
      { row: 0, col: 0, value: 1n }, { row: 0, col: 1, value: 1n },
      { row: 31, col: 0, value: claimed },
    ],
    describe: 'Fibonacci, 32 rows from (1,1)',
  },
  // "I know a preimage that reaches `claimed` after 16 rounds of x -> x^3 + RC."
  'hashchain-16': {
    params: { traceLen: 16, width: 1, constraintDeg: 3 },
    transitions: [(c, n) => sub(n[0], add(mul(mul(c[0], c[0]), c[0]), 987654321n))],
    boundary: (claimed) => [{ row: 15, col: 0, value: claimed }],
    describe: 'knowledge of a 16-round x^3+RC chain preimage',
  },
};

/** Build a prover context for a named statement. */
export const statementCtx = (name) => setup(STATEMENTS[name].params);

/**
 * Verify a proof of a NAMED statement against a claimed public value. Returns false for an unknown
 * name, a malformed proof, or a claim the proof does not support — never throws, so a host binding
 * can hand the verdict straight to a guest.
 */
export function verifyStatement(name, proof, claimed) {
  const st = STATEMENTS[name];
  if (!st) return false;
  try {
    return verify(statementCtx(name), { proof, transitions: st.transitions, boundary: st.boundary(claimed) });
  } catch { return false; }
}

// ── Self-test ────────────────────────────────────────────────────────────────────────────────────
if (import.meta.url === `file://${process.argv[1]}`) {
  const ok = (b) => (b ? 'PASS' : 'FAIL');

  // (a) Fibonacci — the canonical AIR. Two columns, two degree-1 transitions.
  {
    const T = 32;
    const ctx = setup({ traceLen: T, width: 2, constraintDeg: 1 });
    const trace = []; let a = 1n, b = 1n;
    for (let r = 0; r < T; r++) { trace.push([a, b]); const nb = add(a, b); a = b; b = nb; }
    const transitions = [
      (c, n) => sub(n[0], c[1]),
      (c, n) => sub(n[1], add(c[0], c[1])),
    ];
    const boundary = [
      { row: 0, col: 0, value: 1n }, { row: 0, col: 1, value: 1n },
      { row: T - 1, col: 0, value: trace[T - 1][0] },
    ];
    const t0 = Date.now();
    const proof = prove(ctx, { trace, transitions, boundary });
    const ms = Date.now() - t0;
    console.log(`AIR fibonacci  K=${ctx.K} N=${ctx.N}  prove ${ms} ms`);
    console.log(`  honest proof verifies                  : ${ok(verify(ctx, { proof, transitions, boundary }))}`);
    const wrong = boundary.slice(); wrong[2] = { row: T - 1, col: 0, value: add(trace[T - 1][0], 1n) };
    console.log(`  a wrong claimed output is rejected     : ${ok(!verify(ctx, { proof, transitions, boundary: wrong }))}`);
    // a trace that breaks the recurrence must not produce an accepted proof
    const bad = trace.map((r) => r.slice()); bad[7][1] = add(bad[7][1], 1n);
    const badProof = prove(ctx, { trace: bad, transitions, boundary });
    console.log(`  a trace violating the rule is rejected : ${ok(!verify(ctx, { proof: badProof, transitions, boundary }))}`);
  }

  // (b) Proof of knowledge of a preimage — a degree-3 hash chain over a SECRET start value.
  {
    const T = 16, RC = 987654321n;
    const ctx = setup({ traceLen: T, width: 1, constraintDeg: 3 });
    const secret = 1234567n;
    const trace = []; let x = secret;
    for (let r = 0; r < T; r++) { trace.push([x]); x = add(mul(mul(x, x), x), RC); }
    const digest = trace[T - 1][0];
    const transitions = [(c, n) => sub(n[0], add(mul(mul(c[0], c[0]), c[0]), RC))];
    const boundary = [{ row: T - 1, col: 0, value: digest }];
    const t0 = Date.now();
    const proof = prove(ctx, { trace, transitions, boundary });
    console.log(`AIR preimage   K=${ctx.K} N=${ctx.N}  prove ${Date.now() - t0} ms`);
    console.log(`  honest proof verifies                  : ${ok(verify(ctx, { proof, transitions, boundary }))}`);
    const blob = JSON.stringify(proof, (_k, v) => (typeof v === 'bigint' ? v.toString() : v));
    console.log(`  the secret preimage is not in the proof: ${ok(!blob.includes(secret.toString()))}`);
    const other = [{ row: T - 1, col: 0, value: add(digest, 1n) }];
    console.log(`  a different digest is rejected         : ${ok(!verify(ctx, { proof, transitions, boundary: other }))}`);
  }
}
